// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:01b32fc1-1dfe-4f4d-b02a-d757c94915d9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_5qAtxfiJK",
    "aws_user_pools_web_client_id": "1t7u42v3krg3kttfh1p6bivgm3",
    "oauth": {}
};


export default awsmobile;
